<?php

declare(strict_types=1);

return [
    'http://www.w3.org/2000/09/xmldsig#' => [
        'CanonicalizationMethod' => '\SimpleSAML\XMLSecurity\XML\ds\CanonicalizationMethod',
        'DigestMethod' => '\SimpleSAML\XMLSecurity\XML\ds\DigestMethod',
        'DigestValue' => '\SimpleSAML\XMLSecurity\XML\ds\DigestValue',
        'Exponent' => '\SimpleSAML\XMLSecurity\XML\ds\Exponent',
        'KeyInfo' => '\SimpleSAML\XMLSecurity\XML\ds\KeyInfo',
        'KeyName' => '\SimpleSAML\XMLSecurity\XML\ds\KeyName',
        'KeyValue' => '\SimpleSAML\XMLSecurity\XML\ds\KeyValue',
        'Manifest' => '\SimpleSAML\XMLSecurity\XML\ds\Manifest',
        'Modulus' => '\SimpleSAML\XMLSecurity\XML\ds\Modulus',
        'Object' => '\SimpleSAML\XMLSecurity\XML\ds\DsObject',
        'RSAKeyValue' => '\SimpleSAML\XMLSecurity\XML\ds\RSAKeyValue',
        'Reference' => '\SimpleSAML\XMLSecurity\XML\ds\Reference',
        'RetrievalMethod' => '\SimpleSAML\XMLSecurity\XML\ds\RetrievalMethod',
        'Signature' => '\SimpleSAML\XMLSecurity\XML\ds\Signature',
        'SignatureMethod' => '\SimpleSAML\XMLSecurity\XML\ds\SignatureMethod',
        'SignatureProperties' => '\SimpleSAML\XMLSecurity\XML\ds\SignatureProperties',
        'SignatureProperty' => '\SimpleSAML\XMLSecurity\XML\ds\SignatureProperty',
        'SignatureValue' => '\SimpleSAML\XMLSecurity\XML\ds\SignatureValue',
        'SignedInfo' => '\SimpleSAML\XMLSecurity\XML\ds\SignedInfo',
        'Transform' => '\SimpleSAML\XMLSecurity\XML\ds\Transform',
        'Transforms' => '\SimpleSAML\XMLSecurity\XML\ds\Transforms',
        'X509Certificate' => '\SimpleSAML\XMLSecurity\XML\ds\X509Certificate',
        'X509Data' => '\SimpleSAML\XMLSecurity\XML\ds\X509Data',
        'X509IssuerName' => '\SimpleSAML\XMLSecurity\XML\ds\X509IssuerName',
        'X509IssuerSerial' => '\SimpleSAML\XMLSecurity\XML\ds\X509IssuerSerial',
        'X509SerialNumber' => '\SimpleSAML\XMLSecurity\XML\ds\X509SerialNumber',
        'X509SubjectName' => '\SimpleSAML\XMLSecurity\XML\ds\X509SubjectName',
        'XPath' => '\SimpleSAML\XMLSecurity\XML\ds\XPath',
    ],
    'http://www.w3.org/2009/xmldsig11#' => [
        'KeyInfoReference' => '\SimpleSAML\XMLSecurity\XML\dsig11\KeyInfoReference',
        'X509Digest' => '\SimpleSAML\XMLSecurity\XML\dsig11\X509Digest',
    ],
    'http://www.w3.org/2001/10/xml-exc-c14n#' => [
        'InclusiveNamespaces' => '\SimpleSAML\XMLSecurity\XML\ec\InclusiveNamespaces',
    ],
    'http://www.w3.org/2001/04/xmlenc#' => [
        'CarriedKeyName' => '\SimpleSAML\XMLSecurity\XML\xenc\CarriedKeyName',
        'CipherData' => '\SimpleSAML\XMLSecurity\XML\xenc\CipherData',
        'CipherReference' => '\SimpleSAML\XMLSecurity\XML\xenc\CipherReference',
        'CipherValue' => '\SimpleSAML\XMLSecurity\XML\xenc\CipherValue',
        'DataReference' => '\SimpleSAML\XMLSecurity\XML\xenc\DataReference',
        'EncryptedData' => '\SimpleSAML\XMLSecurity\XML\xenc\EncryptedData',
        'EncryptedKey' => '\SimpleSAML\XMLSecurity\XML\xenc\EncryptedKey',
        'EncryptionMethod' => '\SimpleSAML\XMLSecurity\XML\xenc\EncryptionMethod',
        'EncryptionProperties' => '\SimpleSAML\XMLSecurity\XML\xenc\EncryptionProperties',
        'EncryptionProperty' => '\SimpleSAML\XMLSecurity\XML\xenc\EncryptionProperty',
        'KeyReference' => '\SimpleSAML\XMLSecurity\XML\xenc\KeyReference',
        'KeySize' => '\SimpleSAML\XMLSecurity\XML\xenc\KeySize',
        'OAEPparams' => '\SimpleSAML\XMLSecurity\XML\xenc\OAEPparams',
        'ReferenceList' => '\SimpleSAML\XMLSecurity\XML\xenc\ReferenceList',
        'Transforms' => '\SimpleSAML\XMLSecurity\XML\xenc\Transforms',
    ],
];
